# Generated by Django 3.2.7 on 2021-10-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20211002_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
